sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d #encrypt/decrypt secret file
    - curl https://sdk.clould.google.com | bash > /dev/null; # download and install google sdk
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl # update kubectl inside travis environment
    - gcloud auth activate-service-account --key-file service-account.json # login gcp
    # activate-service-account == IAM 
