version: '3'
services: 
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx:
        depends_on: 
            - api
            - react-client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports: 
            - '3050:80'
    api:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes: 
            - /app/node_modules # leave node_modules folder AS IS
            - ./server:/app #copy everything inside /server folder into /app folder under container (except /node_modules)
        depends_on: 
            - postgres
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    react-client:
        build: 
            dockerfile: Dockerfile.dev
            context: ./react-client
        volumes: 
            - /app/node_modules
            - ./react-client:/app
    worker:
        build: 
            dockerfile: Dockerfile.dev
            context: ./worker
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment: 
            - REDIS_HOST=redis
            - REDIS_PORT=6379
                

    